apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ default .Values.iam.namespace .Release.Namespace }}
  labels:
    app: {{ template "iam.app-name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "iam.app-name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "iam.app-name" . }}
        release: {{ .Release.Name }}
        datalayer.io/app: {{ template "iam.app-name" . }}
    spec:
      terminationGracePeriodSeconds: 0
      {{- with .Values.iam.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iam.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: reg-creds
      containers:
        - name: iam
          image: {{ .Values.iam.image }}
          imagePullPolicy: {{ .Values.iam.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.iam.port }}
              protocol: TCP
          {{- if .Values.iam.env }}
          env:
            {{- range $key, $value := .Values.iam.env }}
            - name: {{ $key }}
              {{- if kindIs "map" $value }}
              valueFrom: {{- $value | toYaml | nindent 16}}
              {{- else }}
              value: {{ $value | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.iam.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.iam.volumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
#        - name: iam-sidecar
#          image: {{ .Values.iam.sidecar.image }}
#          imagePullPolicy: {{ .Values.iam.imagePullPolicy }}
#          args: ["proxy", "-p", "8001"]
