cephStorage:
  usersPVC: cephfs-users-pvc
  # Should match storageClass name in ceph-cluster
  storageClassName: ceph-filesystem
  storageOwner:
    # Must match remote kernel container user uid/gid
    uid: '1000'
    gid: '100'
