{{- define "localcsi.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "localcsi.driverName" -}}
local.csi.datalayer.io
{{- end -}}

{{- define "localcsi.labels" -}}
app.kubernetes.io/name: {{ include "localcsi.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{- define "localcsi.selectorLabels" -}}
app: datalayer-local-csi
release: {{ .Release.Name }}
{{- end -}}

{{- define "localcsi.pluginDir" -}}
{{ .Values.driver.kubeletDir }}/plugins/{{ include "localcsi.driverName" . }}
{{- end -}}
