{{- if index .Values "opentelemetry-operator" "enabled" }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: datalayer-collector
{{- with .Values.collector.affinity }}
affinity: {{- toYaml . | nindent 8 }}
{{- end }}
spec:
  # The opentelemetry-collector chart is a good place to look for good configuration
  # Reference: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
  mode: deployment # This configuration is omittable.
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/system
            operator: In
            values:
            - "true"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor#recommended-processors
    processors:
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor
      batch: {}
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor
      # Default memory limiter configuration for the collector based on k8s resource limits.
      memory_limiter:
        # check_interval is the time between measurements of memory usage.
        check_interval: 5s
        # By default limit_mib is set to 80% of ".Values.resources.limits.memory"
        limit_percentage: 80
        # By default spike_limit_mib is set to 25% of ".Values.resources.limits.memory"
        spike_limit_percentage: 25

      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
          labels:
          - tag_name: app.name
            key: datalayer.io/app
            from: pod
          - tag_name: datalayer.pool.name
            key: jupyterpool.datalayer.io/name
            from: pod
          - tag_name: datalayer.pool.status
            key: jupyterpool.datalayer.io/pod-status
            from: pod
          - tag_name: datalayer.pool.user
            key: jupyterpool.datalayer.io/user-uid
            from: pod
          - tag_name: datalayer.pool.type
            key: jupyterpool.datalayer.io/kernel-type
            from: pod
          - tag_name: datalayer.pool.reservation
            key: jupyterpool.datalayer.io/reservation-id
            from: pod
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection

      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor
      resource:
        attributes:
        # Align resource attributes names with prometheus metrics attributes names
        - key: cluster
          action: upsert
          value: '{{ template "observer.runHost" . }}'
        - key: namespace
          action: upsert
          from_attribute: k8s.namespace.name
        - key: pod
          action: upsert
          from_attribute: k8s.pod.name
        - key: instance
          action: upsert
          from_attribute: k8s.pod.uid
        - key: app
          action: upsert
          from_attribute: datalayer.app.name
        # Opentelemetry service specification attributes
        # https://opentelemetry.io/docs/specs/semconv/resource/#service
        # service.name is already set by the code instrumentation in traces
        - key: service.namespace
          action: upsert
          from_attribute: k8s.namespace.name
        - key: service.instance.id
          action: upsert
          from_attribute: k8s.pod.uid
        # Reduce the attributes duplication
        - action: delete
          pattern: k8s\..*

      transform:
        metric_statements:
        # Set metric labels from resource attribute as prometheus does not handle them properly
        - context: datapoint
          statements:
          - set(attributes["cluster"], "{{ template "observer.runHost" . }}")
          - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
          - set(attributes["pod"], resource.attributes["k8s.pod.name"])
          - set(attributes["instance"], resource.attributes["k8s.pod.uid"])
          - set(attributes["app"], resource.attributes["datalayer.app.name"])
          - set(attributes["service_name"], resource.attributes["service.name"])

    exporters:
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter
      # debug:
      #   verbosity: detailed

      # Data sources: metrics
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
      prometheus:
        endpoint: 0.0.0.0:8889
        # namespace: default

      otlp:
        endpoint: {{ default .Values.observer.namespace .Release.Namespace }}-tempo:4317
        tls:
          insecure: true

    extensions:
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
      health_check: {}
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/pprofextension
      pprof: {}
      # https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md
      zpages: {}

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, transform, batch]
          exporters: [prometheus]
{{- end }}
