apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kernels-usage-topic
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
