apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "jupyter.app-name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "jupyter.app-name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "jupyter.app-name" . }}
        release: {{ .Release.Name }}
        datalayer.io/app: {{ template "jupyter.app-name" . }}
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role.datalayer.io/api
                operator: In
                values:
                - "true"
      imagePullSecrets:
            - name: reg-creds
      containers:
        - name: jupyter
          image: {{ .Values.jupyter.image }}
          imagePullPolicy: {{ .Values.jupyter.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.jupyter.port }}
              protocol: TCP
          env:
          - name: DATALAYER_RUN_HOST
            value: {{ .Values.jupyter.env.DATALAYER_RUN_HOST }}
          - name: DATALAYER_CDN_URL
            value: {{ .Values.jupyter.env.DATALAYER_CDN_URL }}
          - name: DATALAYER_RUNTIME_ENV
            value: {{ .Values.jupyter.env.DATALAYER_RUNTIME_ENV }}
          - name: DATALAYER_JWT_ISSUER
            value: {{ .Values.jupyter.env.DATALAYER_JWT_ISSUER }}
          - name: DATALAYER_JWT_SECRET
            value: {{ .Values.jupyter.env.DATALAYER_JWT_SECRET }}
          - name: DATALAYER_JWT_ALGORITHM
            value: {{ .Values.jupyter.env.DATALAYER_JWT_ALGORITHM }}
          - name: DATALAYER_AUTHZ_ENGINE
            value: {{ .Values.jupyter.env.DATALAYER_AUTHZ_ENGINE }}
          - name: DATALAYER_OPENFGA_REST_URL
            value: {{ .Values.jupyter.env.DATALAYER_OPENFGA_REST_URL }}
          - name: DATALAYER_OPENFGA_STORE_ID
            value: {{ .Values.jupyter.env.DATALAYER_OPENFGA_STORE_ID }}
          - name: DATALAYER_OPENFGA_AUTHZ_MODEL_ID
            value: {{ .Values.jupyter.env.DATALAYER_OPENFGA_AUTHZ_MODEL_ID }}
          - name: DATALAYER_SOLR_ZK_HOST
            value: {{ .Values.jupyter.env.DATALAYER_SOLR_ZK_HOST }}
          - name: DATALAYER_SOLR_USERNAME
            valueFrom:
              secretKeyRef:
                name: solr-basic-auth
                key: username
          - name: DATALAYER_SOLR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: solr-basic-auth
                key: password
          - name: DATALAYER_OPERATOR_API_KEY
            value: {{ .Values.jupyter.env.DATALAYER_OPERATOR_API_KEY }}
          - name: DATALAYER_JWT_CACHE_VALIDATE
            value: "false"
          volumeMounts:
          resources:
{{ toYaml .Values.jupyter.resources | indent 12 }} 
#        - name: jupyter-sidecar
#          image: {{ .Values.jupyter.sidecar.image }}
#          imagePullPolicy: {{ .Values.jupyter.imagePullPolicy }}
#          args: ["proxy", "-p", "8001"]
