{{- if and .Values.operator.cloudCredentials.enabled .Values.operator.cloudCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.cloud-credentials-secret-name" . }}
  namespace: {{ default .Values.operator.namespace .Release.Namespace }}
  labels:
    app: {{ template "operator.app-name" . }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.operator.cloudCredentials.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.operator.cloudCredentials.aws.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.operator.cloudCredentials.aws.defaultRegion | quote }}
  AZURE_TENANT_ID: {{ .Values.operator.cloudCredentials.azure.tenantId | quote }}
  AZURE_CLIENT_ID: {{ .Values.operator.cloudCredentials.azure.clientId | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.operator.cloudCredentials.azure.clientSecret | quote }}
  AZURE_SUBSCRIPTION_ID: {{ .Values.operator.cloudCredentials.azure.subscriptionId | quote }}
  AZURE_RESOURCE_GROUP: {{ .Values.operator.cloudCredentials.azure.resourceGroup | quote }}
{{- end }}
