apiVersion: v1
kind: ServiceAccount
metadata:
  name: datalayer-runtimes-companion
  namespace: datalayer-runtimes
# Opt out of auto API credentials to prevent all containers
# to use the service account
automountServiceAccountToken: false
