apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: datalayer-jupyter
  name: datalayer-operator-companion
  labels:
    k8s-app: datalayer-operator-companion
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get"]
