apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datalayer-runtimes-companion-svc
  namespace: datalayer-runtimes
subjects:
- kind: ServiceAccount
  name: datalayer-runtimes-companion
  namespace: datalayer-runtimes
roleRef:
  kind: Role
  name: datalayer-runtimes-companion
  apiGroup: rbac.authorization.k8s.io
