apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: datalayer-jupyter
subjects:
- kind: ServiceAccount
  name: datalayer-operator-companion
  namespace: datalayer-jupyter
roleRef:
  kind: Role
  name: datalayer-operator-companion
  apiGroup: rbac.authorization.k8s.io
