{{ if eq .Values.operator.crds true -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyter-contents.datalayer.io
  annotations:
    helm.sh/resource-policy: keep
spec:
  scope: Namespaced
  group: datalayer.io
  names:
    kind: JupyterContent
    singular: jupyter-content
    plural: jupyter-contents
    shortNames:
      - jc
      - jcs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - git
                    - nfs
                    - s3
                  title: Type of content
                description:
                  type: string
                  title: Content long description.
                source:
                  type: string
                  title: Content source
                  description: |
                    For `git`, its the repository URI.
                    For `nfs`, its the...
                    For `s3`, its the bucket name.
                location:
                  type: string
                  title: Location (for s3).
                subPath:
                  type: string
                  title: Subpath
                  description: |
                    The subpath of the remote content to mount on the local.
                permissions:
                  type: string
                  enum:
                    - ro
                    - rw
                  default: ro
                secret:
                  title: K8S Secret name for accessing the content
                  type: string
              required:
                - type
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.type
          description: Type of content.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create_jupyter_content.message
          description: Message returned after the Jupyter Content creation.
{{- end }}
