{{ if eq .Values.operator.crds true -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyterpools.datalayer.io
spec:
  scope: Namespaced
  group: datalayer.io
  names:
    kind: Jupyterpool
    singular: jupyterpool
    plural: jupyterpools
    shortNames:
      - jp
      - jps
      - jpool
      - jpools
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                cull:
                  type: object
                  properties:
                    seconds:
                      type: integer
                environment:
                  type: string
                size:
                  type: integer
                burningRate:
                  title: Pod credits burning rate per second
                  type: number
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Environment
          type: string
          priority: 0
          jsonPath: .spec.environment
          description: Environment name for the Jupyterpool.
        - name: Size
          type: string
          priority: 0
          jsonPath: .spec.size
          description: Number of pods to maintain in the Jupyterpool.
        - name: BurningRate
          type: string
          priority: 0
          jsonPath: .spec.burningRate
          description: Burning rate (credits per second).
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create_jupyterpool.message
          description: Message returned after the Jupyterpool creation.
        - name: InitialPods
          type: string
          priority: 0
          jsonPath: .status.create_jupyterpool.initial_pods
          description: The initial pods created.
{{- end }}
