{{- if and .Values.operator.kubeletCerts.cert .Values.operator.kubeletCerts.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kubelet-certs
  namespace: {{ default .Values.operator.namespace .Release.Namespace }}
  labels:
    app: {{ template "operator.app-name" . }}
type: Opaque
data:
  tls.crt: {{ .Values.operator.kubeletCerts.cert | b64enc }}
  tls.key: {{ .Values.operator.kubeletCerts.key | b64enc }}
{{- end }}
