apiVersion: v1
kind: ServiceAccount
labels:
  k8s-app: datalayer-runtimes-sa
  chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
metadata:
  name: datalayer-runtimes-sa
  namespace: datalayer-runtimes
# Opt out of auto API credentials to prevent all containers
# to use the service account
automountServiceAccountToken: false
