header:
  license:
    spdx-id: Datalayer
    copyright-owner: Datalayer, Inc.
    copyright-year: 2023-2024
    content: |
      Copyright (c) [year] [owner]

      Datalayer License

  paths-ignore:
    - '**/*.apt'
    - '**/*.cedar'
    - '**/*.dash'
    - '**/*.fga'
    - '**/*.ipynb'
    - '**/*.j2'
    - '**/*.json'
    - '**/*.jupyter-python'
    - '**/*.jupyter-python-remotes'
    - '**/*.mamba'
    - '**/*.md'
    - '**/*.md.gotmpl'
    - '**/*.mod'
    - '**/*.nblink'
    - '**/*.rego'
    - '**/*.sum'
    - '**/*.svg'
    - '**/*.template'
    - '**/*.tsbuildinfo'
    - '**/*.txt'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*_key'
    - '**/*_key.pub'
    - '**/.*'
    - '**/LICENSE.txt'
    - '**/MANIFEST.in'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/schemas'
    - '**/ssh/*'
    - '**/static'
    - '**/themes'
    - '**/typings'
    - '*.bundle.js'
    - '*.map.js'
    - 'LICENSE'
    - 'plane/etc/dockerfiles/datalayer-solr/config/'
    - 'plane/etc/dockerfiles/ingress-nginx-controller/'

  comment: on-failure