{{ if eq .Values.support.clusterType "any" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-ingress
  annotations:
    acme.cert-manager.io/http01-ingress-class: {{ .Values.support.ingressClass }}
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: {{ .Values.support.certificateIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
    nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
    nginx.ingress.kubernetes.io/session-cookie-samesite: None
    nginx.ingress.kubernetes.io/session-cookie-name: support-affinity
    nginx.ingress.kubernetes.io/enable-modsecurity: 'true'
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: 'true'
    traefik.ingress.kubernetes.io/router.tls: 'true'
  labels:
    app: support
spec:
  ingressClassName: {{ .Values.support.ingressClass }}
  tls:
  - hosts:
    - {{ template "support.runHost" . }}
    secretName: {{ template "support.runHost" . }}-datalayer-api-cert-secret
  rules:
  - host: {{ template "support.runHost" . }}
    http:
      paths:
      - path: /api/support
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc
            port: 
              number: {{ .Values.support.port }}
{{- end }}
