imagePullSecrets:
  - name: reg-creds
allowSnippetAnnotations: "true"
controller:
  image:
    image: ingress-nginx-controller
    tag: v1.10.1
    digest: sha256:7d3e2f788cf096e44449113fbea079869b563ce1da17cb7ac032bb5a21fc07ef
  nodeSelector:
    role.datalayer.io/router: "true"
defaultBackend:
  nodeSelector:
    role.datalayer.io/router: "true"
