mailer:
  image:
  imagePullPolicy: Always
  port: 2331
  namespace: datalayer-system
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/system
            operator: In
            values:
            - "true"
  env:
    DATALAYER_SMTP_HOST: ""
    DATALAYER_SMTP_PASSWORD: ""
    DATALAYER_SMTP_PORT: "0"
    DATALAYER_SMTP_USERNAME: ""
