apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ template "mcpservers.app-name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # Trick for CORS bug in starlette middleware
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "false"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "none"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mcpservers.port }}
    name: mcp-servers-http
    protocol: TCP
    targetPort: {{ .Values.mcpservers.port }}
  selector:
    app: {{ template "mcpservers.app-name" . }}
    release: {{ .Release.Name }}
#  externalTrafficPolicy: Local       # Important?!
