{{ if eq .Values.home.clusterType "any" -}}
apiVersion: v1
kind: Service
metadata:
  name: home-redirect-svc
  labels:
    app: home
spec:
  type: ClusterIP
  ports:
  - port: 9700
    targetPort: 9700
    protocol: TCP
{{- end }}
