apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datalayer-jupyter-svc
  namespace: datalayer-jupyter
subjects:
- kind: ServiceAccount
  name: datalayer-jupyter
  namespace: datalayer-api
roleRef:
  kind: Role
  name: datalayer-jupyter
  apiGroup: rbac.authorization.k8s.io
