{{- if eq .Values.ingressClass "datalayer-traefik" }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: growth-auth
  namespace: {{ .Release.Namespace }}
spec:
  forwardAuth:
    address: http://{{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.growth.port }}/api/growth/v1/auth
    trustForwardHeader: true
    # authRequestHeaders:
    #   - "Authorization"
{{- end }}