apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedStorage.sharedFsPVC }}
  namespace: datalayer-jupyter
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ include "sharedStorage.autoStorageSize" . }}
  storageClassName: {{ include "sharedStorage.autoStorageClassName" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedStorage.sharedFsPVC }}
  namespace: datalayer-api
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ include "sharedStorage.autoStorageSize" . }}
  storageClassName: {{ include "sharedStorage.autoStorageClassName" . }}
---
apiVersion: v1
kind: Pod
metadata:
  name: shared-fs-prepare
  namespace: datalayer-jupyter
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/jupyter
            operator: In
            values:
            - "true"
  restartPolicy: OnFailure
  containers:
  - image: busybox:1.36.1-musl
    name: prepare-cephfs
    command:
    - /bin/sh
    - -x
    - -e
    - -c
    - |
      for DIRECTORY in home public datalayer datasets ai-models tmp
      do
        mkdir -pm 775 /mnt/sharedfs/$DIRECTORY
        chmod g+ws /mnt/sharedfs/$DIRECTORY
        chown $KERNEL_UID:$KERNEL_GID /mnt/sharedfs/$DIRECTORY
      done
      sleep 1000
    env:
      - name: KERNEL_UID
        value: "{{ .Values.sharedStorage.storageOwner.uid }}"
      - name: KERNEL_GID
        value: "{{ .Values.sharedStorage.storageOwner.gid }}"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 64Mi
    volumeMounts:
    - mountPath: /mnt/sharedfs
      name: sharedfs-data
  volumes:
  - name: sharedfs-data
    persistentVolumeClaim:
      claimName: {{ .Values.sharedStorage.sharedFsPVC }}
      readOnly: false
