{{ if eq .Values.sharedStorage.storageProvider "azure" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "sharedStorage.autoStorageClassName" . }}
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
  protocol: nfs
{{ end }}
