{{- if and (eq .Values.sharedStorage.storageProvider "aws") .Values.sharedStorage.aws.fileSystemId }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.sharedStorage.aws.fileSystemId | quote }}
  uid: {{ .Values.sharedStorage.aws.uid | quote }}
  gid: {{ .Values.sharedStorage.aws.gid | quote }}
  directoryPerms: "700"
  basePath: "/datalayer-dynamic"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
{{- end }}
