apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "manager.app-name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "manager.app-name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "manager.app-name" . }}
        release: {{ .Release.Name }}
        datalayer.io/app: {{ template "manager.app-name" . }}
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role.datalayer.io/api
                operator: In
                values:
                - "true"
      imagePullSecrets:
            - name: reg-creds
      containers:
        - name: manager
          image: {{ .Values.manager.image }}
          imagePullPolicy: {{ .Values.manager.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.manager.port }}
              protocol: TCP
          {{- if or .Values.manager.env .Values.manager.envValueFrom }}
          env:
            {{- range $key, $value := .Values.manager.envValueFrom }}
            - name: {{ $key }}
              valueFrom: {{- $value | toYaml | nindent 16 }}
            {{- end }}
            {{- range $key, $value := .Values.manager.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /api/manager/version
              port: 9300
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
          resources:
{{ toYaml .Values.manager.resources | indent 12 }} 
#         - name: manager-sidecar
#           image: {{ .Values.manager.sidecar.image }}
#          imagePullPolicy: {{ .Values.manager.imagePullPolicy }}
#           args: ["proxy", "-p", "8001"]
