{{ if eq .Values.jupyterpool.clusterType "gke-NA" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jupyterpool-ingress
  annotations:
    # specify the name of the global IP address resource to be associated with the HTTP(S) Load Balancer.
    kubernetes.io/ingress.global-static-ip-name: datalayer-io-ip
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt
    # controls whether the ingress is modified ‘in-place’,
    # or a new one is created specifically for the HTTP01 challenge.
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: jupyterpool
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - datalayer.io
    secretName: jupyterpool-cert-secret # < cert-manager will store the created certificate in this secret
  rules:
  - host: datalayer.io
    http:
      paths:
      - path: /api/jupyter-server/*
        backend:
          serviceName: {{ .Release.Name }}-svc
          servicePort: 2300
{{- end }}
