apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
  namespace: {{ .Values.namespace }}
  labels:
    app: simple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: simple
          image: {{ .Values.simple.image }}
          securityContext:
            runAsUser: 0
            privileged: true
          ports:
            - containerPort: 9876
              protocol: TCP
          env:
          - name: "USERNAME"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.simpleSecretName }}
                key:  username
          - name: "DATALAYER_LDAP_BIND_PWD"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.simpleSecretName }}
                key: DATALAYER_LDAP_BIND_PWD
