{{ if .Values.simple.ingressMinikube -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-name: datalayer-simple-stick
    nginx.ingress.kubernetes.io/enable-modsecurity: 'true'
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: 'true'
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      set $cookie "datalayer-simple-stick=${http_host}; ${http_cookie}";
#      proxy_set_header Cookie $cookie;
#      if ($http_x_custom_header) {
#        return 403;
#      }
#      more_set_headers "Request-Id: $req_id";
#    nginx.ingress.kubernetes.io/rewrite-target: '/'
spec:
  ingressClassName: nginx
  rules:
  - host: minikube.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.service.name }}
              port:
                number: 9876
{{- end }}
