apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ai-agent.app-name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ai-agent.app-name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "ai-agent.app-name" . }}
        release: {{ .Release.Name }}
        datalayer.io/app: {{ template "ai-agent.app-name" . }}
      annotations:
        karpenter.sh/do-not-disrupt: "true"      
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role.datalayer.io/api
                operator: In
                values:
                - "true"
      imagePullSecrets:
            - name: reg-creds
      containers:
        - name: ai-agent
          image: {{ .Values.ai-agent.image }}
          imagePullPolicy: {{ .Values.ai-agent.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ai-agent.port }}
              protocol: TCP
          {{- if or .Values.ai-agent.env .Values.ai-agent.envValueFrom }}
          env:
            {{- range $key, $value := .Values.ai-agent.envValueFrom }}
            - name: {{ $key }}
              valueFrom: {{- $value | toYaml | nindent 16 }}
            {{- end }}
            {{- range $key, $value := .Values.ai-agent.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /api/ai-agent/version
              port: 4400
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
          resources:
{{ toYaml .Values.ai-agent.resources | indent 12 }} 
