jupyter:
  image: datalayer/jupyter:0.1.1
  imagePullPolicy: Always
  sidecar:
    image: datalayer/whoami:0.0.6
  clusterType: any
  certificateIssuer: letsencrypt
  ingressClass: datalayer-traefik
  port: 9500
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/api
            operator: In
            values:
            - "true"
  envValueFrom:
    DATALAYER_SOLR_USERNAME:
      secretKeyRef:
        name: solr-basic-auth
        key: username
    DATALAYER_SOLR_PASSWORD:
      secretKeyRef:
        name: solr-basic-auth
        key: password
  env:
    DATALAYER_AUTHZ_ENGINE: ""
    DATALAYER_CDN_URL: ""
    DATALAYER_JWT_ALGORITHM: ""
    DATALAYER_JWT_ISSUER: "https://id.datalayer.run"
    DATALAYER_JWT_CACHE_VALIDATE: "false"
    DATALAYER_JWT_SECRET: ""
    DATALAYER_OPENFGA_AUTHZ_MODEL_ID: ""
    DATALAYER_OPENFGA_REST_URL: "http://datalayer-openfga.datalayer-openfga.svc.cluster.local:8080"
    DATALAYER_OPENFGA_STORE_ID: ""
    DATALAYER_OPERATOR_API_KEY: ""
    DATALAYER_OPERATOR_HOST: "datalayer-operator-svc.datalayer-api.svc.cluster.local:2111"
    DATALAYER_RUNTIME_ENV: "prod"
    DATALAYER_RUN_HOST: ""
    DATALAYER_SOLR_ZK_HOST: "solr-datalayer-solrcloud-zookeeper-headless.datalayer-solr.svc.cluster.local"

#  resources:
#    limits:
#      memory: "8192Mi"
#      cpu: "3000m"
