apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "library.app-name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "library.app-name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "library.app-name" . }}
        release: {{ .Release.Name }}
        datalayer.io/app: {{ template "library.app-name" . }}
      annotations:
        karpenter.sh/do-not-disrupt: "true"      
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role.datalayer.io/api
                operator: In
                values:
                - "true"
      imagePullSecrets:
            - name: reg-creds
      containers:
        - name: library
          image: {{ .Values.library.image }}
          imagePullPolicy: {{ .Values.library.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.library.port }}
              protocol: TCP
          {{- if or .Values.library.env .Values.library.envValueFrom }}
          env:
            {{- if .Values.library.sharedFsPVC }}
            - name: 'DATALAYER_SHARED_FS_VOLUME_CLAIM_NAME'
              value: {{ .Values.library.sharedFsPVC }}
            {{- end }}
            {{- range $key, $value := .Values.library.envValueFrom }}
            - name: {{ $key }}
              valueFrom: {{- $value | toYaml | nindent 16 }}
            {{- end }}
            {{- range $key, $value := .Values.library.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /api/library/version
              port: 9800
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
{{ toYaml .Values.library.resources | indent 12 }} 
#         - name: library-sidecar
#           image: {{ .Values.library.sidecar.image }}
#          imagePullPolicy: {{ .Values.library.imagePullPolicy }}
#           args: ["proxy", "-p", "8001"]
          {{- if .Values.library.sharedFsPVC }}
          volumeMounts:
            - name: "sharedfs-data"
              mountPath: "/mnt/sharedfs"
          {{- end }}
      {{- if .Values.library.sharedFsPVC }}
      volumes:
        - name: "sharedfs-data"
          persistentVolumeClaim:
            claimName: {{ .Values.library.sharedFsPVC }}
            readOnly: False
      {{- end }}
