{{ if eq .Values.jupyterpool.clusterType "gke" -}}
#   https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#session_affinity
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: jupyterpool-backend-config
spec:
#  sessionAffinity:
#    affinityType: "CLIENT_IP"
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 9999
{{- end }}
