{{ if eq .Values.jupyterpool.clusterType "eks" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterpool-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
    nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
    nginx.ingress.kubernetes.io/session-cookie-samesite: None
    nginx.ingress.kubernetes.io/session-cookie-name: jupyterpool-affinity
    nginx.ingress.kubernetes.io/enable-modsecurity: 'true'
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: 'true'
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app: jupyterpool
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.jupyterpool.env.DATALAYER_RUN_HOST }}
    secretName: {{ .Values.jupyterpool.env.DATALAYER_RUN_HOST }}-jupyterpool-cert-secret
  rules:
  - host: {{ .Values.jupyterpool.env.DATALAYER_RUN_HOST }}
    http:
      paths:
      - path: /api/jupyter-server
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              number: 2300
{{- end }}
