operator:
  image: datalayer/operator:1.0.6
  sidecar:
    image: datalayer/whoami:0.0.6
  imagePullPolicy: Always
  crds: true
  port: 2111
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role.datalayer.io/api
                operator: In
                values:
                  - "true"
  env:
    AWS_ACCESS_KEY_ID: ""
    AWS_DEFAULT_REGION: ""
    AWS_SECRET_ACCESS_KEY: ""
    DATALAYER_AUTHZ_ENGINE: "openfga"
    DATALAYER_CERT_ISSUER: "letsencrypt"
    DATALAYER_DOCKER_REGISTRY: ""
    DATALAYER_IAM_API_KEY: ""
    DATALAYER_IAM_HOST: "datalayer-iam-svc.datalayer-api.svc.cluster.local:9700"
    DATALAYER_INGRESS_CLASS_NAME: "datalayer-traefik"
    DATALAYER_OPERATOR_API_KEY: ""
    DATALAYER_PUB_SUB_ENGINE: "pulsar"
    DATALAYER_PULSAR_URL: "pulsar://datalayer-pulsar-broker.datalayer-pulsar.svc.cluster.local:6650"
    DATALAYER_RUN_HOST: ""
    DATALAYER_VAULT_TOKEN: ""
    DATALAYER_VAULT_URL: "http://datalayer-vault-internal.datalayer-vault.svc.cluster.local:8200"
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ""
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ""
    OTEL_SDK_DISABLED: "false"
  tolerations: {}
  volumeMounts: {}
  sharedFsPVC: ""
