operator:
  image: datalayer/operator:1.0.19
  sidecar:
    image: datalayer/whoami:0.0.6
  imagePullPolicy: Always
  crds: true
  port: 2111
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role.datalayer.io/api
                operator: In
                values:
                  - "true"
  env:
    AWS_ACCESS_KEY_ID: ""
    AWS_DEFAULT_REGION: ""
    AWS_SECRET_ACCESS_KEY: ""
    DATALAYER_AUTHZ_ENGINE: "openfga"
    DATALAYER_AVAILABLE_KERNELS_MAX_LIFE_SEC: "3600"
    DATALAYER_CERT_ISSUER: "letsencrypt"
    DATALAYER_DOCKER_REGISTRY: ""
    DATALAYER_IAM_API_KEY: ""
    DATALAYER_IAM_HOST: "datalayer-iam-svc.datalayer-api.svc.cluster.local:9700"
    DATALAYER_INGRESS_CLASS_NAME: "datalayer-traefik"
    DATALAYER_KAFKA_PASSWORD: ""
    DATALAYER_KAFKA_URL: "datalayer-kafka-kafka-bootstrap.datalayer-kafka.svc.cluster.local:9092"
    DATALAYER_KAFKA_USERNAME: ""
    DATALAYER_KERNELS_RUN_HOOKS: "false"
    DATALAYER_OPERATOR_API_KEY: ""
    DATALAYER_PUB_SUB_ENGINE: "kafka"
    DATALAYER_PULSAR_URL: "pulsar://datalayer-pulsar-broker.datalayer-pulsar.svc.cluster.local:6650"
    DATALAYER_RUN_URL: ""
    DATALAYER_VAULT_TOKEN: ""
    DATALAYER_VAULT_URL: "http://datalayer-vault-internal.datalayer-vault.svc.cluster.local:8200"
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ""
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ""
    OTEL_SDK_DISABLED: "false"
  tolerations: {}
  volumeMounts: {}
  sharedFsPVC: ""
