apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cephStorage.usersPVC }}
  namespace: datalayer-jupyter
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: {{ .Values.cephStorage.storageClassName }}
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-users-prepare
  namespace: datalayer-jupyter
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/jupyter
            operator: In
            values:
            - "true"
  restartPolicy: OnFailure
  containers:
  - image: busybox:1.36.1-musl
    name: prepare-cephfs
    command:
    - /bin/sh
    - -x
    - -e
    - -c
    - |
      for DIRECTORY in home public datasets tmp
      do
        mkdir -p /mnt/ceph/$DIRECTORY
        chown $KERNEL_UID:$KERNEL_GID /mnt/ceph/$DIRECTORY
      done
      sleep 1000
    env:
      - name: KERNEL_UID
        value: "{{ .Values.cephStorage.storageOwner.uid }}"
      - name: KERNEL_GID
        value: "{{ .Values.cephStorage.storageOwner.gid }}"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 64Mi
    volumeMounts:
    - mountPath: /mnt/ceph
      name: ceph-data
  volumes:
  - name: ceph-data
    persistentVolumeClaim:
      claimName: {{ .Values.cephStorage.usersPVC }}
      readOnly: false
