volumes:
  persistence: true
tls:
  enabled: false
  proxy:
    enabled: false
  broker:
    enabled: false
  zookeeper:
    enabled: false
components:
  functions: false
  toolset: false
  proxy: false
  pulsar_manager: false
kube-prometheus-stack:
  enabled: false
bookkeeper:
  replicaCount: 3
  nodeSelector:
    role.datalayer.io/system: "true"
broker:
  replicaCount: 3
  nodeSelector:
    role.datalayer.io/system: "true"
proxy:
  podMonitor:
    enabled: false
  nodeSelector:
    role.datalayer.io/system: "true"
zookeeper:
  replicaCount: 3
  nodeSelector:
    role.datalayer.io/system: "true"
