apiVersion: v1
description: Datalayer Kafka
name: datalayer-kafka
version: 0.1.0
appVersion: 0.1.0
home: https://datalayer.tech
sources:
  - https://github.com/datalayer/helm-charts/tree/main/charts/datalayer-kafka
icon: https://assets.datalayer.tech/datalayer-square.png
maintainers:
  - name: Datalayer
    email: support@datalayer.io
    url: https://datalayer.io
dependencies:
  - name: strimzi-kafka-operator
    version: "0.45.0"
    repository: "https://strimzi.io/charts"
