apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ template "operator.app-name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "operator.app-name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "operator.app-name" . }}
        release: {{ .Release.Name }}
        datalayer.io/app: {{ template "operator.app-name" . }}
    spec:
      terminationGracePeriodSeconds: 0
      {{- with .Values.operator.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: reg-creds
      containers:
        - name: operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.operator.port }}
              protocol: TCP
          {{- if or .Values.operator.env .Values.operator.envValueFrom }}
          env:
            {{- range $key, $value := .Values.operator.envValueFrom }}
            - name: {{ $key }}
              valueFrom: {{- $value | toYaml | nindent 16 }}
            {{- end }}
            {{- range $key, $value := .Values.operator.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /api/operator/version
              port: 2111
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 15
          {{- with .Values.operator.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.operator.volumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
#        - name: operator-sidecar
#          image: {{ .Values.operator.sidecar.image }}
#          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
#          args: ["proxy", "-p", "8001"]
