apiVersion: v1
kind: Pod
metadata:
  name: mailer
  namespace: {{ default .Values.mailer.namespace .Release.Namespace }}
  labels:
    app: mailer
spec:
  imagePullSecrets:
    - name: reg-creds
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/system
            operator: In
            values:
            - "true"
  restartPolicy: OnFailure
  containers:
  - image: {{ .Values.mailer.image }}
    name: mailer
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 64Mi
