{{- define "contents.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "contents.labels" -}}
app.kubernetes.io/name: {{ include "contents.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{- define "contents.selectorLabels" -}}
app: contents
release: {{ .Release.Name }}
{{- end -}}

{{- define "contents.runHost" -}}
{{- .Values.contents.runHost | replace "https://" "" | replace "http://" "" -}}
{{- end -}}
