sharedStorage:
  sharedFsPVC: shared-fs-pvc
  # sharedStorage.storageProvider -- Will set automatically value depending on the storage provider.
  # Supported value are: "azure" or "ceph"
  storageProvider: "azure"
  # sharedStorage.storageClassName -- Storage class to use
  # If not specified the default value will be inferred from the provider.
  storageClassName: null
  # sharedStorage.storageSize -- Storage size
  # If not specified the default value will be inferred from the provider.
  storageSize: null
  storageOwner:
    # Must match remote kernel container user uid/gid
    uid: '1000'
    gid: '100'
