hub:
  baseUrl: '/api/jupyterhub'
  allowNamedServers: true
  config:
    Authenticator:
      allowed_users:
        - 'charlie'
    DummyAuthenticator:
      password: 'brown'
    JupyterHub:
      authenticator_class: dummy
singleuser:
  cmd: jupyterhub-singleuser
  defaultUrl: '/lab'
  image:
    name: jupyter/scipy-notebook
    tag: 2023-07-11
  storage:
    # Decide if you want storage to be provisioned dynamically (dynamic), or if you want to attach existing storage (static), or don’t want any storage to be attached (none).
    type: none
ingress:
  enabled: true
  hosts:
    - minikube.local
