proxy:
  secretToken: 
hub:
  baseUrl: /api/jupyterhub
  allowNamedServers: true
  config:
    JupyterHub:
      authenticator_class: pam
    Authenticator:
      allowed_users:
        - admin
      admin_users:
        - datalayer
    PAMAuthenticator:
      create_system_users: true
singleuser:
  image:
    name: jupyter/scipy-notebook
    tag: 2023-07-11
  defaultUrl: /lab
