proxy:
  secretToken: 
hub:
  baseUrl: /api/jupyterhub
  allowNamedServers: true
  config:
    JupyterHub:
      authenticator_class: dummy
    Authenticator:
      allowed_users:
        - admin
      admin_users:
        - datalayer
    DummyAuthenticator:
      password: '' # '123'
singleuser:
  image:
    name: jupyter/scipy-notebook
    tag: 2023-07-11
  defaultUrl: /lab
