jump:
  clusterType: ovh
  image: datalayer/jump:0.0.6
  imagePullPolicy: Always
  sidecar:
    image: datalayer/whoami:0.0.6
  env:
    DATALAYER_SOLR_ZK_HOST: "solr-datalayer-solrcloud-zookeeper-headless.datalayer-solr.svc.cluster.local"
    DATALAYER_LDAP_HOST: "datalayer-ldap-openldap"
    DATALAYER_KEYCLOAK_SCHEME_HOST: "https://datalayer.io"
