jump:
  image: datalayer/jump:0.0.6
  imagePullPolicy: Always
  port: 2223
  sidecar:
    image: datalayer/whoami:0.0.6
#  resources:
#    limits:
#      memory: "8192Mi"
#      cpu: "3000m"
  env:
    DATALAYER_RUN_URL: ""
