affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role.datalayer.io/jupyter
          operator: In
          values:
          - "true"
collectors:
  kubernetes:
    enabled: true
k8s-metacollector:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/system
            operator: In
            values:
            - "true"
falco:
  rules_files:
    # Order matters to apply override the rule should be loaded first.
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco-incubating_rules.yaml
    - /etc/falco/falco-sandbox_rules.yaml
    - /etc/falco/rules.d
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/jupyter
            operator: In
            values:
            - "true"
falcoctl:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/jupyter
            operator: In
            values:
            - "true"
  config:
    artifact:
      install:
        refs:
          - falco-rules:3
          - falco-incubating-rules:4
          - falco-sandbox-rules:4
          - ghcr.io/falcosecurity/plugins/plugin/k8smeta:0.2.1
      follow:
        refs:
          - falco-rules:3
          - falco-incubating-rules:4
          - falco-sandbox-rules:4
falcosidekick:
  enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role.datalayer.io/system
            operator: In
            values:
            - "true"
  # See https://github.com/falcosecurity/falcosidekick/blob/master/config_example.yaml
  config:
    # debug: true
    # Not working ??
    # templatedfields: "Dkey:{{ or (index .OutputFields \"k8s.ns.name\") \"bar\" }},k8s_labels:{{ printf \"%q\" (or (index .OutputFields \"k8s.pod.labels\") \"error\") }}"
    kafka:
      hostport: datalayer-kafka-kafka-bootstrap.datalayer-kafka.svc.cluster.local:9092
      topic: falco-events
    prometheus:
  grafana:
    dashboards:
      enabled: false
  prometheusRules:
    # Default rules have wrong metrics nomenclature:
    # https://github.com/falcosecurity/charts/pull/805
    enabled: false
  serviceMonitor:
    enabled: true
    additionalLabels:
      monitoring.datalayer.io/enabled: "true"
      monitoring.datalayer.io/instance: "observer"
  # webui:
  #   enabled: true
