{{- if .Values.ray.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ray.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "ray.app-name" . }}
{{- end }}
