apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "ray.app-name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.ray.serviceType }}
  ports:
    - port: {{ .Values.ray.port }}
      name: ray-http
      protocol: TCP
      targetPort: {{ .Values.ray.port }}
  selector:
    app: {{ include "ray.app-name" . }}
    release: {{ .Release.Name }}
