apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.simpleSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "simple.name" . }}
    chart: {{ template "simple.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "kubernetes.io/simple"
data:
  username: {{ default "" .Values.api.username | b64enc | quote }}
  password: {{ default "" .Values.api.password | b64enc | quote }}
  DATALAYER_LDAP_BIND_PWD: {{ default "" .Values.secret.DATALAYER_LDAP_BIND_PWD | b64enc | quote }}
