apiVersion: v1
kind: Service
metadata:
  name: {{ template "scheduler.service-name" . }}
  {{ if eq .Values.scheduler.clusterType "gke" -}}
  annotations:
    cloud.google.com/backend-config: '{"default": "scheduler-backend-config"}'
  {{- end }}
  labels:
    app: {{ template "scheduler.app-name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.scheduler.port }}
    name: scheduler-http
    protocol: TCP
    targetPort: {{ .Values.scheduler.port }}
  selector:
    app: {{ template "scheduler.app-name" . }}
    release: {{ .Release.Name }}
